<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-09-26T16:05:37+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'UTC',
];
