<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-09-26T16:23:27+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.4.3',
    'version_db_installed' => '20180716000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1537977937,
        'latest_version' => '8.4.3',
    ],
];
