<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-09-26T16:05:00+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'C5 Timeless',
        ],
    ],
];
